web:
  container_name: web1
  build: .
  volumes:
    - ./:/var/www/
  ports:
    - "80:80"
  links:
    - mysql

mysql:
  container_name: mysql
  image: mysql:latest
  volumes:
    - ./mysqlData:/var/lib/mysql
  environment:
    MYSQL_ROOT_PASSWORD: "derp"