web:
  container_name: atWeb1
  build: .
  volumes:
    - ./:/var/www/
  ports:
    - "9080:80"
  links:
    - mysql

mysql:
  container_name: atMysql
  image: mysql:latest
  volumes:
    - ./mysqlData:/var/lib/mysql
  environment:
    MYSQL_ROOT_PASSWORD: "derp"
